apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: agent-workflow-testing
  namespace: infra
spec:
  cluster: mgmt
  repositoryRef:
    name: agent-workflow-testing-source
  git:
    ref: master
    folder: manifests/apps/agent-workflow-testing
  namespace: agent-workflow-testing
